// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieApp.DAL;

#nullable disable

namespace MovieApp.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221120171940_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MovieApp.DomainModels.MovieDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Genre")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom the project and his team to disaster.",
                            Genre = 1,
                            Title = "Inception",
                            UserId = 1,
                            Year = 2010
                        },
                        new
                        {
                            Id = 2,
                            Description = "Eight years after the Joker's reign of anarchy, Batman, with the help of the enigmatic Catwoman, is forced from his exile to save Gotham City from the brutal guerrilla terrorist Bane.",
                            Genre = 1,
                            Title = "The Dark Knight Rises",
                            UserId = 1,
                            Year = 2012
                        },
                        new
                        {
                            Id = 3,
                            Description = "Three buddies wake up from a bachelor party in Las Vegas, with no memory of the previous night and the bachelor missing. They make their way around the city in order to find their friend before his wedding.",
                            Genre = 2,
                            Title = "The Hangover",
                            UserId = 1,
                            Year = 2009
                        },
                        new
                        {
                            Id = 4,
                            Description = "Two years after the bachelor party in Las Vegas, Phil, Stu, Alan, and Doug jet to Thailand for Stu's wedding. Stu's plan for a subdued pre-wedding brunch, however, goes seriously awry.",
                            Genre = 2,
                            Title = "The Hangover Part II",
                            UserId = 1,
                            Year = 2011
                        },
                        new
                        {
                            Id = 5,
                            Description = "A sole survivor tells of the twisty events leading up to a horrific gun battle on a boat, which began when five criminals met at a seemingly random police lineup.",
                            Genre = 3,
                            Title = "The Usual Suspects",
                            UserId = 1,
                            Year = 1995
                        },
                        new
                        {
                            Id = 6,
                            Description = "An altar boy is accused of murdering a priest, and the truth is buried several layers deep.",
                            Genre = 3,
                            Title = "Primal Fear",
                            UserId = 1,
                            Year = 1996
                        },
                        new
                        {
                            Id = 7,
                            Description = "After a wealthy San Francisco banker is given an opportunity to participate in a mysterious game, his life is turned upside down as he begins to question if it might really be a concealed conspiracy to destroy him.",
                            Genre = 4,
                            Title = "The Game",
                            UserId = 1,
                            Year = 1997
                        },
                        new
                        {
                            Id = 8,
                            Description = "Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.",
                            Genre = 4,
                            Title = "Se7en",
                            UserId = 1,
                            Year = 1995
                        },
                        new
                        {
                            Id = 9,
                            Description = "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
                            Genre = 4,
                            Title = "Pulp Fiction",
                            UserId = 1,
                            Year = 1994
                        });
                });

            modelBuilder.Entity("MovieApp.DomainModels.UserDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("FavoriteGenre")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FavoriteGenre = 2,
                            FirstName = "Darko",
                            LastName = "Angelovski",
                            Password = "?|???plL4?h??N{",
                            Username = "dare1992"
                        });
                });

            modelBuilder.Entity("MovieApp.DomainModels.MovieDto", b =>
                {
                    b.HasOne("MovieApp.DomainModels.UserDto", "User")
                        .WithMany("Movies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieApp.DomainModels.UserDto", b =>
                {
                    b.Navigation("Movies");
                });
#pragma warning restore 612, 618
        }
    }
}
